### PR TITLE
Fixed manage preferences description text view height to 300

### PR DESCRIPTION
**Pull request by Nevazhnovu**

### CODE REVIEW

**Comment by andresilveirah** [comment]
@Nevazhnovu do we need to do anything else in this PR?

**Comment by Nevazhnovu** [comment]
@andresilveirah I think this PR is good as it is since it is tackle one specific issue. I have a couple more issues to address, all of them are mentioned by Chaitanya in DIA-2356 but I think I'll address them in a separate PR

**Comment by Nevazhnovu** [comment]
@andresilveirah I think this PR is good as it is since it tackles one specific issue. I have a couple more issues to address, all of them are mentioned by Chaitanya in DIA-2356 but I think I'll address them in a separate PR

**Comment by andresilveirah** [comment]
Sounds good to me ✅

**Pull request merged**
