### PR TITLE
add swift package manager support

### PR DESCRIPTION
**Pull request by SaschaDegenhardt**

### CODE REVIEW

**Comment by DennisHirschgaenger** [comment]
When using this, the library crashes in MessageWebViewController.swift:24 since the resource GDPRJSReceiver.js is not copied to the bundle.

There is no solution to solve this with SPM 5.2. Swift 5.3 brings support for adding resources with [SE-0271](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md). So for now the PR should be closed and reopened once Swift 5.3 is available

**Comment by andresilveirah** [comment]
Thank you @SaschaDegenhardt for opening the PR and thank you @DennisHirschgaenger for taking the effort and trying this branch. 

I'll keep this issue open (every maintainer knows an open issue is a constant reminder) so we don't forget to get back to it when Swift 5.3 is available.

**Comment by ivanlisovyi** [comment]
Hi @andresilveirah. Do you have an ETA for the SPM support?

**Comment by andresilveirah** [comment]
Closing in favour of #241

**Pull request closed without merging**
