### PR TITLE
[DIA-564] delete custom consent 

### PR DESCRIPTION
**Pull request by Nevazhnovu**

### CODE REVIEW

**Comment by carmelo-iriti** [comment]
@andresilveirah should we add an explanation/usage on the README about this new api?

**Comment by andresilveirah** [comment]
@Nevazhnovu can merge this branch on top of `develop`, force push so I can review?

**Comment by Nevazhnovu** [comment]
@andresilveirah done

**Review by andresilveirah — APPROVED** [review]
🚀

**Pull request merged**
